esphome:
  name: ir-projectorremote
  friendly_name: IR-ProjectorRemote

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: "5R+NdDTC2EcfxfMHO/13uQlHztXOF8lI/GrmpqvD7BE="

ota:
  - platform: esphome
    password: "4ecd347f71175d3baa4f168aace64f93"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # optional, just to silence warning:
  # min_auth_mode: WPA2

  ap:
    ssid: "Ir-Projectorremote"
    password: "VUL27Zbadd17"

captive_portal:



remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "Projector Power"
    id: projector_power
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xE21D
          command_repeats: 1

  - platform: template
    name: "Projector Volume Up"
    id: projector_vol_up
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xEE11
          command_repeats: 1

  - platform: template
    name: "Projector Volume Down"
    id: projector_vol_down
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xEA15
          command_repeats: 1

  - platform: template
    name: "Projector Mute"
    id: projector_mute
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xFD02
          command_repeats: 1

  - platform: template
    name: "Projector OK"
    id: projector_ok
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xF40B
          command_repeats: 1

  - platform: template
    name: "Projector Up"
    id: projector_up
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xF609
          command_repeats: 1

  - platform: template
    name: "Projector Down"
    id: projector_down
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xFE01
          command_repeats: 1

  - platform: template
    name: "Projector Left"
    id: projector_left
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xF50A
          command_repeats: 1

  - platform: template
    name: "Projector Right"
    id: projector_right
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xF708
          command_repeats: 1

  - platform: template
    name: "Projector Menu"
    id: projector_menu
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xE01F
          command_repeats: 1

  - platform: template
    name: "Projector Source"
    id: projector_source
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xE11E
          command_repeats: 1

  - platform: template
    name: "Projector Home"
    id: projector_home
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xE51A
          command_repeats: 1

  - platform: template
    name: "Projector Return"
    id: projector_return
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFD02
          command: 0xE41B
          command_repeats: 1