esphome:
  name: meteo
  friendly_name: Meteo

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "LA2hULTT4BNPCANqIIlLJayrGbF7ySzIYc2BGuLTUyg="

ota:
  - platform: esphome
    password: "17f4567a3299e662c0bc1561547236e4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Meteo Fallback Hotspot"
    password: "risF9fYFGoI5"

captive_portal:

# ---- I2C BUS (BME/BMP280) ----
i2c:
  sda: D2      # GPIO4
  scl: D1      # GPIO5
  scan: true

sensor:
  - platform: bme280_i2c      # <--- important: _i2c
    temperature:
      name: "Meteo Temperature"
    humidity:
      name: "Meteo Humidity"
    pressure:
      name: "Meteo Pressure"
    address: 0x76             # change to 0x77 if logs show that
    update_interval: 30s